name: Frontend CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    name: Frontend Tests
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        working-directory: frontend/teacher_schedules
        run: npm install

      - name: Executar testes
        working-directory: frontend/teacher_schedules/src/__tests__
        run: npm test

  frontend-build:
    runs-on: ubuntu-latest
    name: Frontend Build
    needs: frontend-tests
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        working-directory: frontend/teacher_schedules
        run: npm install

      - name: Executar build
        working-directory: frontend/teacher_schedules
        run: npm run build

      - name: Salvar artefato de build
        uses: actions/upload-artifact@v4
        with:
          name: build-frontend
          path: frontend/teacher_schedules/dist/

  notify:
    runs-on: ubuntu-latest
    name: Enviar notificação por e-mail
    needs: [frontend-tests, frontend-build]
    steps:
      - uses: actions/checkout@v3

      - name: Instalar sendemail
        run: sudo apt-get update && sudo apt-get install -y sendemail libio-socket-ssl-perl libnet-ssleay-perl

      - name: Dar permissão de execução ao script
        run: chmod +x .github/scripts/send_email.sh

      - name: Enviar e-mail com script
        run: .github/scripts/send_email.sh
        env:
          EMAIL_DESTINATARIO: ${{secrets.EMAIL_DESTINATARIO}}